### ISSUE TITLE
PC鯖取得について

### ISSUE THREAD

**Issue by takutaku716** [nao20010128nao/Wisecraft#1]
PC鯖のほうの人数や、詳細の取得はできるのですが、MODやプラグインの取得が最新バージョンからできなくなりました

**Comment by Lesmiscore** [comment]
Modの事でしょうか(プラグインが取得できないのは仕様なので)
最新版(Wisecraft 3.1)ということは、ping結果をエクスポートできると思いますので、ping結果をエクスポートして頂き、こちらに添付して下さい。エクスポートは、サーバー詳細画面の上矢印のボタンから可能です。(バイナリファイルなので、DropBox等にアップロードする必要があります。)
また、ページを移動させた際に、クラッシュ等は発生しましたか?
もし可能であれば、サーバーのIPアドレス及びポートもお教え願います。

**Comment by takutaku716** [comment]
あ、プラグインは無理なのですね
了解です
ping結果のエクスポートも了解です
14時頃になるかもしれませんが送信します
クラッシュ等は発生していません

**Comment by Lesmiscore** [comment]
了解しました。
返信をお待ちしております。

2016/08/25 11:41 "takutaku716" notifications@github.com:

**Comment by takutaku716** [comment]
あー、変身してなかった；；
エクスポートしたファイルを覗いてみたのですが(すいません)
modの取得はできていたようですが、表示されていなかったようです

2017-03-07 16:24 GMT+09:00 nao20010128nao <notifications@github.com>:
